spring:
  jpa:
    show-sql: false
    database-platform: com.nwnu.blockchain.repository.sqlite.config.SQLiteDialect
    generate-ddl: true
sqlite:
  dbName: block.db
db:
  levelDB: true
  rocksDB: false
version: 1
# 使用一个节点
singeNode: ${SingeNode:true}
name: ${NAME:name1}
appId: ${APP_ID:app1}
managerUrl: ${MANAGER_URL:http://140.143.245.186:8091/}